# Generated by Django 5.0.4 on 2025-02-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('produkt_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=255)),
                ('cena', models.CharField(max_length=50)),
                ('lokalizacja', models.CharField(max_length=255)),
                ('stan', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('kategoria', models.CharField(max_length=100)),
                ('data_pobrania', models.DateField()),
                ('historia_cen', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'produkty',
            },
        ),
    ]
